// <auto-generated />
using System;
using Cinema.Web.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230114163702_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema.Web.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfTickets")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.HasIndex("MovieId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Cinema.Web.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Description = "Experience the once-in-a-generation movie event, exclusively in cinemas. Set more than a decade after the events of the first film, AVATAR 2 begins to tell the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive and the tragedies they endure. The latest in the groundbreaking fantasy saga from director James Cameron",
                            ImageUrl = "/thumbnails/avatar.png",
                            Name = "Avatar: The Way of Water"
                        },
                        new
                        {
                            MovieId = 2,
                            Description = "She’s more than just a toy. She’s part of the family. From the most prolific minds in horror—James Wan, the filmmaker behind the Saw, Insidious and The Conjuring franchises, and Blumhouse, the producer of the Halloween films, The Black Phone and The Invisible Man—comes a fresh new face in terror. M3GAN is a marvel of artificial intelligence, a life-like doll programmed to be a child’s greatest companion and a parent’s greatest ally.",
                            ImageUrl = "/thumbnails/megan.png",
                            Name = "M3GAN"
                        },
                        new
                        {
                            MovieId = 3,
                            Description = "From Academy Award®-winning director and writer Sam Mendes, EMPIRE OF LIGHT is an intimate and moving story about love, friendship, and connection, set in a coastal town in Southern England against the social turmoil of the early 1980s. Hilary (Olivia Colman), a woman with a difficult past and an uneasy present, is part of a makeshift family at the old Empire Cinema on the seafront. When Stephen (Micheal Ward) is hired to work in the cinema, the two find an unlikely attraction and discover the healing power of movies, music and community.",
                            ImageUrl = "/empire_of_light.png",
                            Name = "Empire of Light"
                        },
                        new
                        {
                            MovieId = 4,
                            Description = "Based on the comical and moving # 1 New York Times bestseller, A Man Called Otto tells the story of Otto Anderson (Tom Hanks), a grumpy widower who is very set in his ways. When a lively young family moves in next door, he meets his match in quick-witted and very pregnant Marisol, leading to an unlikely friendship that will turn his world upside-down. Experience a funny, heartwarming story about how some families come from the most unexpected places.",
                            ImageUrl = "/thumbnails/a_man_called_otto.png",
                            Name = "A Man Called Otto"
                        });
                });

            modelBuilder.Entity("Cinema.Web.Models.Booking", b =>
                {
                    b.HasOne("Cinema.Web.Models.Movie", "Movie")
                        .WithMany("Bookings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Cinema.Web.Models.Movie", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
